language: node_js

node_js:
  - 6

os:
  - linux
  - osx

notifications:
  irc: "irc.freenode.org#travis"

install:
  - npm install -g codecov

script:
  - istanbul cover node_modules/jasmine/bin/jasmine.js
  - codecov
