language: node_js

node_js:
  - 6

notifications:
  irc: "irc.freenode.org#travis"

after_script: istanbul cover ./node_modules/jasmine-node/bin/jasmine-node.js . --captureExceptions spec/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
