language: node_js

node_js:
  - 6

os:
  - linux
  - osx

notifications:
  irc: "irc.freenode.org#travis"

after_script: istanbul cover ./node_modules/jasmine/bin/jasmine.js --captureExceptions && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
