language: node_js

node_js:
  - 6

notifications:
  irc: "irc.freenode.org#travis"

after_script: NODE_ENV=test ./node_modules/istanbul/index.js cover  ./node_modules/jasmine/bin/jasmine.js --captureExceptions spec/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
